simplepages/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('simplepages.views',
    (r'^auto-url-prepend.js$', 'auto_url_prepend_js'),
)

simplepages/models.py
from django.db import models
from django.db.models import fields
from django.utils.html import escape
from django import forms
from django.conf import settings
from django.contrib import admin
from django.contrib.sites.models import Site


# check for settings or else use defaults
APPEND_SLASH =  getattr(settings, 'SIMPLEPAGES_APPEND_SLASH', True)
PREPEND_SLASH = getattr(settings, 'SIMPLEPAGES_PREPEND_SLASH', True)
IMAGE_DIR = getattr(settings, 'SIMPLEPAGES_IMAGE_DIR', 'images')
PREPOP_PAGE_URL = getattr(settings, 'SIMPLEPAGES_PREPOP_PAGE_URL', True)


class SiteSectionManager(models.Manager):

    def menu_items(self):
        return self.get_query_set().filter(show_in_nav__exact=True)

class SiteSection(models.Model):

    name = models.CharField(max_length=255)
    url = models.CharField(max_length=100, unique=True, blank=False)
    show_in_nav = models.BooleanField(default=True, db_index=True)
    order = models.PositiveIntegerField('Display Order', blank=True, null=True);
    
    class Meta:
        ordering = ('order', 'name')

    def save(self):
        # if enabled, check to ensure the urls start and end with slashes
        if APPEND_SLASH and not self.url.endswith('/'):
            self.url = self.url + '/'
        if PREPEND_SLASH and not self.url.startswith('/'):
            self.url = '/' + self.url

        super(SiteSection, self).save() # call the "real" save() method

    def __unicode__(self):
        return u'%s' % self.name
    
    objects = SiteSectionManager()

class SiteSectionAdmin(admin.ModelAdmin):

    prepopulated_fields = {'url': ('name',)}
    list_display = ('name', 'url', 'order', 'show_in_nav')
    search_fields = ('url', 'name')

admin.site.register(SiteSection, SiteSectionAdmin)


class PageManager(models.Manager):

    def menu_items(self):
        return self.get_query_set().filter(show_in_nav__exact=True).order_by(
                'order', 'nav_title')

class Page(models.Model):

    site_section = models.ForeignKey(SiteSection)
    url = models.CharField('URL', max_length=100, unique=True,
            help_text="Example: '/about-us/contact/'")
    title = models.CharField('Page Title', max_length=200)
    image = models.ImageField(upload_to=IMAGE_DIR,  # media root is automatically prepended
            blank=True)
    content = models.TextField(blank=True)
    show_in_nav = models.BooleanField(default=False, db_index=True,
            help_text='Check this box if this page should be shown in '
            'the primary navigation.')
    nav_title = models.CharField(max_length=150, blank=True,
            help_text='The link text that will show in the navigation menu')
    order = models.PositiveIntegerField(blank=True, null=True,
            help_text="The order this item should appear in the menu, defaults "
            "to alphabetical if order isn't specified");
    html_title = models.CharField(max_length=250, blank=True,
            help_text='This is the browser title')
    meta_description = models.TextField(blank=True)
    meta_keywords = models.TextField(blank=True)
    template_name = models.CharField('template name', max_length=70, blank=True,
            help_text="Example: 'pages/contact_page.html'. If this isn't "
            "provided, the system will use 'pages/default.html'.")
    registration_required = models.BooleanField('registration required',
            help_text='If this is checked, only logged-in users will be '
            'able to view the page.')

    class Meta:
        ordering = ('order', 'url',)

    def img_src(self):
        return settings.MEDIA_URL + self.image

    def save(self):
        # if enabled, check to ensure the urls start and end with slashes
        if APPEND_SLASH and not self.url.endswith('/'):
            self.url = self.url + '/'
        if PREPEND_SLASH and not self.url.startswith('/'):
            self.url = '/' + self.url
        super(Page, self).save() # call the "real" save() method

    def __unicode__(self):
        return u'%s -- %s' % (self.url, self.title)

    def get_absolute_url(self):
        return self.url

    objects = PageManager()

class PageAdminForm(forms.ModelForm):

    class Meta:
        model = Page

    content = forms.CharField(
                widget=forms.Textarea(attrs={'class': 'simple-html-editor',
                    'rows': 15, 'cols': 70}))

class PageAdmin(admin.ModelAdmin):
    
    form = PageAdminForm
    fieldsets = (
        (None, {'fields': ('site_section', 'url', 'title', 'image', 'content')}),
        ('HTML Header Values', {'fields': ('html_title', 'meta_description', 'meta_keywords', ),'classes': ('collapse',)}),
        ('Nav Menu Setup', {'fields': ('show_in_nav', 'nav_title', 'order'),'classes': ('collapse',)}),
        ('Advanced options', {'classes': ('collapse',), 'fields': ('registration_required', 'template_name')}),
    )
    list_display = ('url', 'title', 'order', 'site_section')
    list_filter = ('site_section',)
    search_fields = ('url', 'title')
    ordering = ('url', 'order')

    class Media:

        js = []
        if PREPOP_PAGE_URL:
            js.append('/simplepages/auto-url-prepend.js')

admin.site.register(Page, PageAdmin)

simplepages/views.py
from django.core.xheaders import populate_xheaders
from django.core.exceptions import ObjectDoesNotExist
from django.template import loader, RequestContext
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, Http404
from django.conf import settings

from simplepages.models import Page, SiteSection

DEFAULT_TEMPLATE = 'pages/default.html'


def page(request, url):
    """Page view.

    Models: `simplepages.page`
    Templates: Uses the template defined by the `template_name` field,
        or `staticpages/default.html` if template_name is not defined.
    """
    if not url.startswith('/'):
        url = "/" + url
    
    # Fix as the APPEND_SLASH setting doesn't work with
    # the flatpages/simplepages app
    try:
        f = Page.objects.get(url__exact=url)    
    except ObjectDoesNotExist:
        if not url.endswith('/') and settings.APPEND_SLASH:
            url = url + '/'
            f = get_object_or_404(Page, url__exact=url)
        else:
            raise Http404

    # If registration is required for accessing this page, and the user isn't
    # logged in, redirect to the login page.
    if f.registration_required and not request.user.is_authenticated():
        from django.contrib.auth.views import redirect_to_login
        return redirect_to_login(request.path)

    if f.template_name:
        t = loader.select_template((f.template_name, DEFAULT_TEMPLATE))
    else:
        t = loader.get_template(DEFAULT_TEMPLATE)

    c = RequestContext(request, {
        'page': f,
        'request': request,
    })
    response = HttpResponse(t.render(c))
    populate_xheaders(request, response, Page, f.id)

    return response


def auto_url_prepend_js(request):
    sections = SiteSection.objects.all()
    c = RequestContext(request, {
        'sections': sections,
        })
    t = loader.get_template('pages/auto_url_prepend.js')
    response = HttpResponse(t.render(c), mimetype='application/javascript')

    return response

simplepages/templates/pages/default.html
{% extends 'pages/header_settings.html' %}

{% load page_tags %}
{% block content %}
    <h1>{{ page.title }}</h1>
    <div id="content-block">
        {% if page.image %}
            <img src="{{ page.get_image_url }}" />
        {% endif %}
        
        {% if page.content %}
            {{ page.content|autolinebreaks }}
        {% else %}
            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed vel tellus. Nulla faucibus, felis et dictum rutrum, tortor nunc convallis lorem, nec sodales justo urna sit amet velit. Nam posuere. Curabitur lorem lectus, pellentesque semper, sollicitudin sed, interdum in, sapien. Sed mollis purus id sapien. Maecenas nisl erat, venenatis quis, vulputate at, congue congue, nisl. Maecenas at est vitae nisl molestie dictum. Nullam a justo nec nisi adipiscing iaculis. Nullam egestas. Sed auctor, eros sit amet dignissim placerat, sem neque posuere ligula, id semper tortor metus et purus. Maecenas elementum adipiscing ipsum. Fusce orci. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce eu pede. Sed ac est. Sed vulputate pellentesque lorem. Nulla velit velit, fermentum eget, aliquet vitae, laoreet a, urna. Proin congue velit eu velit. Praesent mollis erat vel nunc. Nulla eget lacus.</p>
        {% endif %}
    </div>
{% endblock %}

simplepages/templates/pages/header_settings.html
{% extends 'base.html' %}

{% block html_title %}{% if page.html_title %}{{ page.html_title }}{% else %}{{ page.title }}{% endif %}{% endblock %}

{% block meta_description %}{{ page.meta_description }}{% endblock %}

{% block meta_keywords %}{{ page.meta_keywords }}{% endblock %}

{% block site_section %}{{ page.site_section.url }}{% endblock %}

simplepages/templates/pages/main_menu.html
<ul>
     {% for menu in main_menu %}
        <li {% if menu.current %} class="current"{% endif %}><a href="{{ menu.url }}">{{ menu.name }}</a>
            {% if menu.page_set.menu_items %}
                <ul>
                    {% for page in menu.page_set.menu_items %}
                        <li>
                            <a href="{{ page.url }}"{% ifequal page.url request.path %} class="current"{% endifequal %}>{{ page.nav_title }}</a>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </li> 
    {% endfor %}
</ul>

simplepages/templates/pages/top_menu.html
<ul>
     {% for menu in main_menu %}
        <li {% if menu.current %} class="current"{% endif %}><a href="{{ menu.url }}">{{ menu.name }}</a>
            {% if menu.page_set.menu_items %}
                <ul>
                    {% for page in menu.page_set.menu_items %}
                        <li>
                            <a href="{{ page.url }}"{% ifequal page.url request.path %} class="current"{% endifequal %}>{{ page.nav_title }}</a>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </li> 
    {% endfor %}
</ul>

simplepages/templates/sample_base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
    <title>{% block html_title %}{% endblock %}</title>
    <meta name="description" content="{% block meta_description %}{% endblock %}" />
    <meta name="keywords" content="{% block meta_keywords %}{% endblock %}" />
    {% block extra-head %}{% endblock %}
</head>
<body class="{% block site_section %}{% endblock %}">
<div id="container">
    <div id="page"  class="clearfix">		
        <div id="header">
            <div id="menu">
                {% load page_tags %}{% main_menu request %}
		    </div>
        </div>
    
		<div id="content">           	
            {% autoescape off %}
                {% block content %}{% endblock %}
            {% endautoescape %}
        </div><!-- end content -->
    </div><!-- end page -->

 	<div id="footer">
        <center>&copy;{% now "Y" %}</center>
    </div>
</div>

{% if user.is_staff %}
    {# Determining if we should load the javascript for displaying admin links #}
    <script type="text/javascript" src="{{ MEDIA_URL }}/admin/js/browse_edit.js"></script>
{% endif %}
</body>
</html>
